import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {fixture} from './fixture.js';import {DEFINITIONS} from '../shared/modules.js';import {validateDocument,parseDocument,prepareDocument,writeDocument} from '../shared/model.js';import {agenda,eventsFor} from '../shared/schedule.js';import {totals,ordered} from '../modules/show-day/model.js';
const rows={
 venue:{version:1,items:[{id:'venue',name:'劇場候補',date:'2026-10-10',status:'held',holdUntil:'2026-10-05',fee:100000,paid:50000,paymentDue:'2026-10-08',loadIn:'09:00',loadOut:'22:00',contact:'担当役割',notes:''}]},
 rights:{version:1,workName:'作品',author:'作者',runningMinutes:90,scriptNotes:'',staff:'',items:[{id:'rights',name:'許諾確認',contact:'制作担当',date:'2026-10-05',status:'pending',confirmedDate:null,evidence:''}]},
 'show-day':{version:1,items:[{id:'goods',name:'販売',date:'2026-10-10',time:'13:00',category:'goods',assignee:'物販役割',status:'completed',quantity:10,price:500,notes:''},{id:'trouble',name:'対応',date:'2026-10-10',time:'12:00',category:'trouble',assignee:'案内役割',status:'pending',quantity:0,price:0,notes:''}]}
};function doc(id){const d=fixture();d.project.modules[id]={id,status:'in-progress',startDate:null,dueDate:null,progress:0,alerts:[],data:structuredClone(rows[id])};return d;}
test('FINAL-01: 14-module demo and old data round-trip',async()=>{for(const id of Object.keys(rows)){const d=doc(id);assert.deepEqual(parseDocument(JSON.stringify(prepareDocument(d))).project.modules[id],d.project.modules[id]);assert.equal(d.project.modules.budget.data.plannedSales[0].quantity,80);}const d=parseDocument(await readFile(new URL('../samples/demo.json',import.meta.url),'utf8'));assert.equal(Object.keys(d.project.modules).length,14);assert.equal(Object.keys(DEFINITIONS).length,14);});
test('FINAL-02: reservation, hold and payment have unique IDs and payment stops overdue when settled',()=>{const d=doc('venue'),b=d.project.modules.venue.data;const e=eventsFor(d.project).filter(e=>e.moduleId==='venue');assert.equal(e.length,3);assert.equal(new Set(e.map(e=>e.id)).size,3);assert.equal(agenda(d.project,'2026-10-09').overdue.length,2);b.items[0].paid=100000;assert.equal(agenda(d.project,'2026-10-09').overdue.length,1);b.items[0].status='cancelled';assert.equal(agenda(d.project,'2026-10-11').overdue.length,0);});
test('FINAL-03: confirmed rights need date and evidence; not-needed stops alerts',()=>{const d=doc('rights'),r=d.project.modules.rights.data.items[0];r.status='confirmed';assert.ok(validateDocument(d).some(i=>i.path.endsWith('evidence')));assert.ok(validateDocument(d).some(i=>i.path.endsWith('confirmedDate')));r.evidence='制作担当の確認記録';r.confirmedDate='2026-10-05';assert.equal(validateDocument(d).length,0);assert.equal(agenda(d.project,'2026-10-06').overdue.length,0);r.status='not-needed';r.confirmedDate=null;r.evidence='';assert.equal(validateDocument(d).length,0);});
test('FINAL-04: goods revenue, unresolved issues, chronological report and no settlement changes',()=>{const d=doc('show-day'),b=d.project.modules['show-day'].data;assert.deepEqual(totals(b),{revenue:5000,quantity:10,unresolved:1});assert.equal(ordered(b)[0].id,'trouble');assert.ok(DEFINITIONS['show-day'].report(d.project,b).indexOf('対応')<DEFINITIONS['show-day'].report(d.project,b).indexOf('販売'));assert.equal(d.project.modules.settlement,undefined);b.items[1].status='completed';assert.equal(totals(b).unresolved,0);});
const invalid=[['venue',d=>d.items[0].paid=100001],['venue',d=>d.items[0].holdUntil=null],['venue',d=>{d.items[0].status='booked';d.items[0].date=null;}],['venue',d=>d.items[0].loadOut='08:00'],['venue',d=>d.items[0].loadIn='24:00'],['venue',d=>d.items[0].paymentDue='2026-02-30'],['venue',d=>{d.items[0].status='booked';d.items[0].fee=Number.MAX_SAFE_INTEGER;d.items.push({...d.items[0],id:'overflow'});}],['rights',d=>d.runningMinutes=.5],['rights',d=>d.items[0].status='bad'],['rights',d=>d.items[0].confirmedDate='2026-02-30'],['show-day',d=>d.items[0].quantity=-1],['show-day',d=>d.items[0].price=.5],['show-day',d=>d.items[0].time='24:00'],['show-day',d=>d.items[0].date=null],['show-day',d=>d.items[1].quantity=1],['show-day',d=>{d.items[0].quantity=Number.MAX_SAFE_INTEGER;d.items[0].price=2;}]];
invalid.forEach(([id,change],i)=>test(`FINAL-05: invalid ${id} #${i+1} preserves saved content`,()=>{const d=doc(id),saved=JSON.stringify(d),storage={setItem:()=>assert.fail('must not write')};change(d.project.modules[id].data);assert.throws(()=>writeDocument(storage,d));assert.throws(()=>parseDocument(JSON.stringify(d)));assert.equal(JSON.parse(saved).project.title,'架空公演');}));
