import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {fixture} from './fixture.js';import {DEFINITIONS} from '../shared/modules.js';import {validateDocument,parseDocument,prepareDocument,writeDocument} from '../shared/model.js';import {agenda,eventsFor} from '../shared/schedule.js';
import {totals} from '../modules/settlement/model.js';import {warnings,ordered} from '../modules/stage-operations/model.js';import {publicationText} from '../modules/program/model.js';
const defaults={
 'front-desk':{version:1,changeFund:10000,guidance:'案内',items:[{id:'front',name:'掲示',category:'sign',assignee:'受付',date:'2026-10-01',needed:2,ready:1,status:'preparing',notes:''}]},
 settlement:{version:1,items:[{id:'income',name:'売上',kind:'income',category:'ticket',amount:150000,settled:100000,date:'2026-10-01',notes:''},{id:'expense',name:'会場費',kind:'expense',category:'venue',amount:100000,settled:50000,date:'2026-10-01',notes:''}]},
 program:{version:1,printDate:'2026-10-10',items:[{id:'program',name:'挨拶',category:'contribution',assignee:'代表',date:'2026-10-01',text:'本文',status:'requested'}]},
 'stage-operations':{version:1,items:[{id:'stage',name:'搬入',date:'2026-10-01',startTime:'09:00',endTime:'10:00',department:'舞台',place:'入口',people:3,assignee:'舞台担当',notes:'',status:'planned'}]}
};
function doc(id){const d=fixture();d.project.modules[id]={id,status:'in-progress',startDate:null,dueDate:null,progress:0,alerts:[],data:structuredClone(defaults[id])};return d;}
test('EXT-01/06: sample and four modules preserve old budget and unknown fields through JSON',async()=>{for(const id of Object.keys(defaults)){const d=doc(id);d.project.extra={note:'keep'};const copy=parseDocument(JSON.stringify(prepareDocument(d)));assert.deepEqual(copy.project.modules[id],d.project.modules[id]);assert.deepEqual(copy.project.modules.budget,d.project.modules.budget);assert.deepEqual(copy.project.extra,d.project.extra);}const sample=parseDocument(await readFile(new URL('../samples/demo.json',import.meta.url),'utf8'));assert.equal(Object.keys(sample.project.modules).length,Object.keys(DEFINITIONS).length);});
test('EXT-02: readiness and float stay independent of actual expenses',()=>{const d=doc('front-desk');const b=d.project.modules['front-desk'].data;assert.equal(validateDocument(d).length,0);assert.deepEqual(DEFINITIONS['front-desk'].metrics(d.project,b).map(x=>x[1]),['1件','1個','10,000円']);b.items[0].status='completed';assert.ok(validateDocument(d).length);b.items[0].ready=2;assert.equal(validateDocument(d).length,0);assert.equal(agenda(d.project,'2026-10-02').overdue.length,0);b.items[0].status='not-needed';b.items[0].ready=0;assert.equal(agenda(d.project,'2026-10-02').overdue.length,0);assert.ok(DEFINITIONS['front-desk'].announcement(d.project,b).includes('費用とは別'));});
test('EXT-03: accrual profit, cash, receivable and payable are distinct',()=>{const d=doc('settlement');const b=d.project.modules.settlement.data;assert.deepEqual(totals(b),{income:150000,expense:100000,received:100000,paid:50000,profit:50000,cash:50000,receivable:50000,payable:50000});b.items[0].settled=150000;assert.equal(totals(b).cash,100000);assert.equal(agenda(d.project,'2026-10-02').overdue.length,1);d.project.ticket.priceCategories[0].price=4000;assert.equal(totals(b).income,150000);b.items[1].amount=200000;assert.equal(totals(b).profit,-50000);});
test('EXT-04: program master-linked text and receipt remove collection deadline only',()=>{const d=doc('program'),b=d.project.modules.program.data;assert.ok(publicationText(d.project,b).includes('架空公演'));d.project.title='新しい公演';assert.ok(publicationText(d.project,b).includes('新しい公演'));assert.equal(agenda(d.project,'2026-10-02').overdue.length,1);b.items[0].status='received';assert.equal(agenda(d.project,'2026-10-02').overdue.length,0);assert.equal(eventsFor(d.project).filter(e=>e.moduleId==='program').length,2);});
test('EXT-05: sorted timeline warns same-place overlaps, permits parallel departments and excludes cancelled work',()=>{const d=doc('stage-operations'),b=d.project.modules['stage-operations'].data;const r=b.items[0];b.items.unshift({...r,id:'second',name:'仕込み',startTime:'09:30',endTime:'11:00'});assert.equal(warnings(d.project,b).length,1);assert.equal(validateDocument(d).length,0);assert.equal(ordered(b)[0].id,'stage');b.items[0].department='照明';assert.equal(warnings(d.project,b).length,0);b.items[0].department='舞台';b.items[0].startTime='10:00';assert.equal(warnings(d.project,b).length,0);b.items.forEach(r=>r.status='cancelled');assert.equal(agenda(d.project,'2026-10-02').overdue.length,0);});
const invalid=[
 ['front-desk',d=>d.changeFund=-1],['front-desk',d=>d.items[0].ready=3],['front-desk',d=>d.items[0].needed=.5],['front-desk',d=>d.items[0].date='2026-02-30'],['front-desk',d=>{d.items[0].needed=Number.MAX_SAFE_INTEGER;d.items.push({...d.items[0],id:'overflow'});}],
 ['settlement',d=>d.items[0].settled=150001],['settlement',d=>d.items[0].amount=.5],['settlement',d=>d.items[0].kind='bad'],['settlement',d=>d.items[0].date='2026-02-30'],['settlement',d=>{d.items[0].amount=Number.MAX_SAFE_INTEGER;d.items.push({...d.items[0],id:'overflow'});}],
 ['program',d=>d.items[0].status='bad'],['program',d=>{d.items[0].status='approved';d.items[0].text='';}],['program',d=>d.printDate='bad'],
 ['stage-operations',d=>d.items[0].startTime='24:00'],['stage-operations',d=>d.items[0].endTime='08:00'],['stage-operations',d=>d.items[0].date=null],['stage-operations',d=>d.items[0].people=.5]
];invalid.forEach(([id,change],i)=>test(`EXT-06: invalid ${id} #${i+1} rejects saving and import`,()=>{const d=doc(id),saved=JSON.stringify(d),store={setItem:()=>assert.fail('must not save')};change(d.project.modules[id].data);assert.ok(validateDocument(d).length);assert.throws(()=>writeDocument(store,d));assert.throws(()=>parseDocument(JSON.stringify(d)));assert.equal(JSON.parse(saved).project.title,'架空公演');}));
