import {checker,validTime,safeSum,csv} from '../../shared/common.js';
export const defaults=()=>({version:1,items:[]});
export function totals(d){const revenue=d.items.filter(r=>r.category==='goods').reduce((sum,r)=>sum+BigInt(r.quantity)*BigInt(r.price),0n);if(revenue>BigInt(Number.MAX_SAFE_INTEGER))throw new Error('物販売上が安全な整数範囲を超えています。');return {revenue:Number(revenue),quantity:safeSum(d.items.filter(r=>r.category==='goods').map(r=>r.quantity)),unresolved:d.items.filter(r=>r.category==='trouble'&&r.status==='pending').length};}
export function validate(d,base){const c=checker(base);c.rows(d.items,'items').forEach((r,i)=>{if(!r)return;const p=`items.${i}`;c.text(r.name,`${p}.name`,true);c.text(r.assignee,`${p}.assignee`);c.text(r.notes,`${p}.notes`);c.date(r.date,`${p}.date`);if(r.date===null)c.error(`${p}.date`,'記録日を入力してください。');if(!validTime(r.time))c.error(`${p}.time`,'正しい時刻を入力してください。');c.choice(r.category,`${p}.category`,['reception','seating','goods','trouble','announcement']);c.choice(r.status,`${p}.status`,['pending','completed']);c.number(r.quantity,`${p}.quantity`);c.number(r.price,`${p}.price`);if(r.category!=='goods'&&(r.quantity!==0||r.price!==0))c.error(`${p}.quantity`,'物販以外の数量と単価は0にしてください。');});if(!c.issues.length)try{totals(d);}catch(e){c.error('items',e.message);}return c.issues;}
export const metrics=(p,d)=>{const t=totals(d);return [['記録',`${d.items.length}件`],['物販参考売上',`${t.revenue.toLocaleString('ja-JP')}円`],['物販数量',`${t.quantity}個`],['未対応トラブル',`${t.unresolved}件`]];};
export const ordered=d=>[...d.items].sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time)||a.name.localeCompare(b.name));
export const events=(p,d)=>d.items.map(r=>({title:`当日：${r.name}`,date:r.date,time:r.time,status:r.status==='completed'?'completed':'planned',relatedItemId:r.id}));
export const report=(p,d)=>[p.title,...ordered(d).map(r=>`${r.date} ${r.time}（日本時間） ${r.name} · ${r.category} · ${r.assignee||'担当未定'} · ${r.status}${r.category==='goods'?` · ${r.quantity}個 × ${r.price}円`:''}${r.notes?'\n'+r.notes:''}`)].join('\n\n');
export const exportCSV=(p,d)=>csv([['内容','日付','時刻（日本時間）','区分','担当役割','状態','数量','単価','物販参考売上','備考'],...ordered(d).map(r=>[r.name,r.date,r.time,r.category,r.assignee,r.status,r.quantity,r.price,r.category==='goods'?BigInt(r.quantity)*BigInt(r.price):0,r.notes])]);
